const BlockedAdultContent = [
    "pornhub.com", "xvideos.com", "xnxx.com", "xhamster.com", "redtube.com",
    "youporn.com", "onlyfans.com", "brazzers.com", "chaturbate.com", "livejasmin.com",
    "bongacams.com", "stripchat.com", "cam4.com", "myfreecams.com", "camsoda.com",
    "flirt4free.com", "adultfriendfinder.com", "fetlife.com", "literotica.com", "asstr.org",
    "luscious.net", "hentai-foundry.com", "furaffinity.net", "e621.net", "rule34.xxx",
    "nhentai.net", "hanime.tv", "javhd.com", "dmm.co.jp", "dlsite.com",
    "fakku.net", "erome.com", "imagefap.com", "motherless.com", "daftsex.com",
    "spankbang.com", "eporner.com", "youjizz.com", "txxx.com", "tube8.com",
    "naughtyamerica.com", "bangbros.com", "realitykings.com", "mofos.com", "twistys.com",
    "digitalplayground.com", "babes.com", "teamskeet.com", "vixen.com", "blacked.com",
    "tushy.com", "deeper.com", "kink.com", "pornhd.com", "xconfessions.com",
    "sexart.com", "x-art.com", "metart.com", "hegre.com", "playboy.com",
    "penthouse.com", "hustler.com", "adultempire.com", "aebn.net", "gamelink.com",
    "adultdvdempire.com", "freeones.com", "iafd.com", "tnaflix.com", "elephanttube.com",
    "beeg.com", "cliphunter.com", "drtuber.com", "xtube.com", "fuq.com",
    "heavy-r.com", "perfectgirls.net", "pornpics.com", "nudography.com", "babe.today",
    "pichunter.com", "celebjihad.com", "thefappeningblog.com", "kindgirls.com", "babesandstars.com",
    "brazzersnetwork.com", "realitykings.com", "bangbrosnetwork.com", "mofosnetwork.com", "teamskeet.com",
    "adulttime.com", "pornhubpremium.com", "evilangel.com", "julesmjordan.com", "private.com"
  ];
  
  const BlockedGamblingSites = [
    "bet365.com", "betway.com", "williamhill.com", "paddypower.com", "skybet.com",
    "ladbrokes.com", "coral.co.uk", "unibet.com", "bwin.com", "888sport.com",
    "betfair.com", "bovada.lv", "betonline.ag", "5dimes.eu", "mybookie.ag",
    "pinnacle.com", "betfred.com", "10bet.com", "22bet.com", "1xbet.com",
    "marathonbet.com", "betvictor.com", "sportsbet.com.au", "neds.com.au", "tab.com.au",
    "pointsbet.com", "fanduel.com", "draftkings.com", "foxbet.com", "betmgm.com",
    "caesarssportsbook.com", "barstoolsportsbook.com", "wynn.com", "betrivers.com", "unibet.com",
    "betamerica.com", "twinspires.com", "4njbets.com", "sugarhouse.com", "partypoker.com",
    "pokerstars.com", "fulltilt.com", "ggpoker.com", "888poker.com", "winamax.fr",
    "partypoker.com", "acr-poker.eu", "blackchippoker.eu", "ignitioncasino.eu", "betonline.ag",
    "sportsbetting.ag", "betfair.com", "betdaq.com", "matchbook.com", "smarkets.com",
    "casumo.com", "leovegas.com", "mrgreen.com", "rizk.com", "dunder.com",
    "karamba.com", "partycasino.com", "jackpotcity.com", "rubyfortune.com", "spinpalace.com",
    "royalvegas.com", "betsson.com", "betsafe.com", "nordicbet.com", "casoo.com",
    "playojo.com", "videoslots.com", "slotsmillion.com", "casinoeuro.com", "betspin.com",
    "sloty.com", "spinit.com", "genesiscasino.com", "casinocruise.com", "vegashero.com",
    "europacasino.com", "mansionbet.com", "32red.com", "grosvenorcasinos.com", "meccabingo.com",
    "galacasino.com", "foxbet.com", "livescorebet.com", "tonybet.com", "cloudbet.com",
    "stake.com", "roobet.com", "bitstarz.com", "bitcasino.io", "fortunejack.com"
  ];
  
  const BlockedPhishingMalwareScam = [
    "secure-bank-login.com", "paypal-account-verify.net", "amazon-order-confirmation.co",
    "microsoft365-update.com", "google-security-alert.net", "apple-id-confirm.com",
    "netflix-account-update.co", "facebook-security-check.net", "crypto-wallet-verify.com",
    "irs-tax-refund.co", "usps-tracking-update.com", "fedex-shipment-notice.net",
    "ups-package-delivery.co", "dhl-express-tracking.com", "wellsfargo-secure-login.net",
    "chase-online-banking.co", "bankofamerica-verification.com", "citibank-account-alert.net",
    "capitalone-security-check.com", "amex-card-update.net", "discover-account-verify.co",
    "paypal-resolution-center.com", "ebay-buyer-protection.net", "amazon-prime-renewal.co",
    "netflix-billing-update.com", "hulu-account-reactivation.net", "spotify-premium-offer.co",
    "apple-icloud-sync.com", "google-drive-share.net", "onedrive-storage-upgrade.co",
    "dropbox-file-recovery.com", "linkedin-job-offer.net", "indeed-resume-update.co",
    "monster-job-match.com", "glassdoor-salary-info.net", "ziprecruiter-application-status.co",
    "instagram-verified-badge.com", "twitter-account-security.net", "facebook-friend-request.co",
    "snapchat-filter-unlock.com", "tiktok-follower-boost.net", "youtube-copyright-notice.co",
    "twitch-prime-gaming.com", "steam-game-key.net", "origin-account-login.co",
    "epic-games-free.com", "psn-network-status.net", "xbox-live-gold.co",
    "nintendo-eshop-sale.com", "blizzard-account-verify.net", "ea-origin-access.co",
    "ubisoft-connect-login.com", "rockstar-social-club.net", "gog-game-redeem.co",
    "humble-bundle-gift.com", "itch-io-developer.net", "gamejolt-indie-game.co",
    "kongregate-flash-game.com", "newgrounds-animation.net", "miniclip-game-coins.co",
    "roblox-robux-generator.com", "fortnite-v-bucks.net", "minecraft-premium-account.co",
    "leagueoflegends-rp.com", "dota2-battle-pass.net", "csgo-skin-trader.co",
    "overwatch-loot-box.com", "hearthstone-card-pack.net", "worldofwarcraft-gold.co",
    "runescape-membership.com", "eveonline-plex.net", "guildwars2-gems.co",
    "blackdesert-pearls.com", "elderscrollsonline-crowns.net", "finalfantasy14-gil.co",
    "fifa-ultimate-team.com", "nba2k-vc-coins.net", "madden-mut-coins.co",
    "clashofclans-gems.com", "candycrush-gold-bars.net", "pokemongo-pokecoins.co",
    "coinbase-wallet-restore.com", "binance-trade-bot.net", "metamask-seed-phrase.co",
    "ledger-wallet-update.com", "trezor-firmware-upgrade.net", "blockchain-wallet-recovery.co",
    "myetherwallet-login.com", "trustwallet-token-swap.net", "pancakeswap-liquidity.co",
    "uniswap-token-bridge.com", "aave-defi-lending.net", "compound-interest-calc.co",
    "1inch-exchange-swap.com", "sushiswap-yield-farm.net", "curve-finance-pool.co"
  ];
  
  export const BlockedUrl = [
    ...BlockedAdultContent,
    ...BlockedGamblingSites,
    ...BlockedPhishingMalwareScam
  ];